const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function c(){const ctx=vm.createContext({console,Date,JSON});vm.runInContext(fs.readFileSync('src/SeguimientoApi.gs','utf8'),ctx);ctx.cuentaActualSeguimiento_=()=>({ok:true,usuario:{rol:'COORDINACION',coordinacion_id:'C1',usuario:'uno'}});ctx.leerTabla=()=>[{unidad_id:'U1',clues:'MCSSA000001',nombre_unidad:'Uno',coordinacion_id:'C1',activo:true},{unidad_id:'U2',clues:'MCSSA000002',nombre_unidad:'Dos',coordinacion_id:'C2',activo:true}];ctx.HOJAS={UNIDADES:'CAT_UNIDADES'};ctx.esVerdadero=x=>x===true;ctx.esAdmin=u=>u.rol==='ADMIN';ctx.rolDeCuenta=u=>u.rol;return ctx;}
test('ámbito actual limita coordinación y rechaza una CLUES ajena',()=>{const ctx=c();assert.equal(ctx.identidadSeguimiento_({boleto:'x',periodo:'2026-09'}).unidades.length,1);assert.throws(()=>ctx.identidadSeguimiento_({boleto:'x',periodo:'2026-09',unidad_id:'MCSSA000002'}));});
test('persona sólo accede a unidad vigente, incluso dentro de coordinación',()=>{const ctx=c();ctx.cuentaActualSeguimiento_=()=>({ok:true,usuario:{rol:'PROMOTOR',coordinacion_id:'C1',unidad_id:'U1'}});assert.equal(ctx.identidadSeguimiento_({boleto:'x',periodo:'2026-09'}).unidades[0].id,'MCSSA000001');ctx.cuentaActualSeguimiento_=()=>({ok:true,usuario:{rol:'PROMOTOR',coordinacion_id:'C2',unidad_id:'U1'}});assert.equal(ctx.identidadSeguimiento_({boleto:'x',periodo:'2026-09'}).unidades.length,0);});
test('sesión inválida impide leer las fuentes',()=>{const ctx=c();ctx.cuentaActualSeguimiento_=()=>({ok:false,code:'BOLETO_INVALIDO',message:'Entre otra vez'});assert.throws(()=>ctx.identidadSeguimiento_({boleto:'x',periodo:'2026-09'}),/Entre otra vez/);});
test('atención rechaza estado, fecha inexistente y fórmulas; permite texto seguro',()=>{const ctx=c();assert.throws(()=>ctx.validarAtencionPreventiva_({estado_atencion:'CERRADO'}));assert.throws(()=>ctx.validarAtencionPreventiva_({estado_atencion:'ABIERTA',fecha_compromiso:'2026-02-30'}));assert.equal(ctx.validarAtencionPreventiva_({estado_atencion:'EN_PROCESO',comentario:'=1+1',responsable:'Uno',version:0}).comentario,"'=1+1");});
test('versión debe coincidir y los IDs de la fuente son calculados',()=>{const ctx=c();assert.throws(()=>ctx.comprobarVersionPreventiva_({VERSION:2},1),/cambió/);assert.equal(ctx.comprobarVersionPreventiva_(null,0),1);assert.equal(ctx.comprobarVersionPreventiva_({VERSION:2},2),3);});
test('la anotación actual elige la mayor versión y conserva filas históricas',()=>{const ctx=c(),rows=[{PERIODO:'2026-09',UNIDAD_ID:'MCSSA000001',PENDIENTE_ID:'P1',VERSION:2,COMENTARIO:'Segundo',ESTADO:'ATENDIDA'},{PERIODO:'2026-09',UNIDAD_ID:'MCSSA000001',PENDIENTE_ID:'P1',VERSION:1,COMENTARIO:'Original',ESTADO:'ABIERTA'}];ctx.leerTabla=()=>rows;const p=[{id:'P1',unidad_id:'MCSSA000001'}];ctx.anotacionesPreventivas_(p,'2026-09');assert.equal(p[0].comentario,'Segundo');assert.equal(p[0].version,2);assert.equal(rows[1].COMENTARIO,'Original');});
test('puente ambiguo se resuelve contra todo el catálogo antes del ámbito',()=>{const ctx=c(),puente=[{clues_metas:'MCSSA000001',clues_sis:'MCIMB000001'},{clues_metas:'MCSSA000002',clues_sis:'MCIMB000001'}],id=ctx.identidadSeguimiento_({boleto:'x',periodo:'2026-09'});assert.equal(ctx.canonicalizarSeguimiento_('MCIMB000001',id.universo,puente),null);assert.equal(id.seleccion.length,1);});
test('un corte nuevo que retira una unidad no recupera su cifra anterior',()=>{const ctx=c();vm.runInContext(fs.readFileSync('src/FuentesPreventivas.gs','utf8'),ctx);const row=(id,total)=>({unidad_id:id,periodo:'2026-09',recurso_id:'R1',instrumento:'AUDIT',total});const doc=(cut,rows)=>({version:1,fuente:'NOMINAL',ambito:'JS19',corte:cut,sha256:'a'.repeat(64),filas:rows});const id=ctx.identidadSeguimiento_({boleto:'x',periodo:'2026-09'});const docs=ctx.mapearDocumentosSeguimiento_([doc('2026-09-28',[row('MCSSA000001',50),row('MCSSA000002',10)]),doc('2026-09-30',[row('MCSSA000002',20)])],id.universo,[]);assert.equal(ctx.seleccionarFuentesPreventivas(docs,'2026-09',['MCSSA000001']).nominal.length,0);});
test('fecha de preparación no se presenta como corte confirmado de origen',()=>{const ctx=c();vm.runInContext(fs.readFileSync('src/FuentesPreventivas.gs','utf8'),ctx);const d={version:1,fuente:'CUBOS',ambito:'JS19',corte:'2026-09-30',sha256:'a'.repeat(64),auditoria:{corte_confirmado:false},filas:[{unidad_id:'MCSSA000001',periodo:'2026-08',instrumento:'AUDIT',total:10}]};const r=ctx.seleccionarFuentesPreventivas([d],'2026-08',['MCSSA000001']);assert.equal(r.cubos[0].corte,null);assert.equal(r.cubos[0].estado,'CORTE_DESCONOCIDO');assert.equal(r.fuentes[0].corte,null);});
test('guardar atención responde éxito, agrega historia y rechaza reintento obsoleto',()=>{const ctx=c(),originalRead=ctx.leerTabla,rows=[];ctx.leerTabla=n=>n==='ATENCION_PREVENTIVA'?rows:originalRead(n);ctx.datosSeguimiento_=()=>({pendientes:[{id:'P1',unidad_id:'MCSSA000001'}]});ctx.registrarEvento=()=>{throw Error('No invocar auditoría bajo otro bloqueo');};let held=false;ctx.LockService={getScriptLock:()=>({waitLock:()=>{held=true;},hasLock:()=>held,releaseLock:()=>{held=false;}})};ctx.hojaAtencionPreventiva_=()=>({getLastRow:()=>rows.length+1,getRange:(row)=>{assert.equal(row,rows.length+2);return {setNumberFormat(){return this;},setValues(values){const r={};ctx.COLUMNAS_ATENCION_PREVENTIVA.forEach((k,i)=>r[k]=values[0][i]);rows.push(r);}}}});const p={boleto:'x',periodo:'2026-09',unidad_id:'MCSSA000001',pendiente_id:'P1',version:0,comentario:'Original',estado_atencion:'ABIERTA'};assert.equal(ctx.atenderPreventivo(p).ok,true);assert.equal(rows.length,1);assert.equal(ctx.atenderPreventivo(p).code,'CONFLICTO');p.version=1;p.comentario='Segundo';assert.equal(ctx.atenderPreventivo(p).version,2);assert.equal(rows.length,2);assert.equal(rows[0].COMENTARIO,'Original');assert.equal(held,false);});
